{"url": "https://api.github.com/repos/mozilla/node-firefox/issues/comments/72240788", "html_url": "https://github.com/mozilla/node-firefox/issues/20#issuecomment-72240788", "issue_url": "https://api.github.com/repos/mozilla/node-firefox/issues/20", "id": 72240788, "user": {"login": "tofumatt", "id": 90871, "avatar_url": "https://avatars2.githubusercontent.com/u/90871?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tofumatt", "html_url": "https://github.com/tofumatt", "followers_url": "https://api.github.com/users/tofumatt/followers", "following_url": "https://api.github.com/users/tofumatt/following{/other_user}", "gists_url": "https://api.github.com/users/tofumatt/gists{/gist_id}", "starred_url": "https://api.github.com/users/tofumatt/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tofumatt/subscriptions", "organizations_url": "https://api.github.com/users/tofumatt/orgs", "repos_url": "https://api.github.com/users/tofumatt/repos", "events_url": "https://api.github.com/users/tofumatt/events{/privacy}", "received_events_url": "https://api.github.com/users/tofumatt/received_events", "type": "User", "site_admin": false}, "created_at": "2015-01-30T17:48:34Z", "updated_at": "2015-01-30T17:48:34Z", "author_association": "MEMBER", "body_html": "<p>Right, but if I understand the chain correctly that means we aren't doing <code>.catch()</code> all the way up our Promises chain so somewhere the error is hidden...</p>\n<p><a href=\"https://github.com/mozilla/node-firefox-connect/blob/master/index.js#L10\">https://github.com/mozilla/node-firefox-connect/blob/master/index.js#L10</a></p>\n<p>That would mean having to wrap the <code>client.connect</code> bit in a <code>try/catch</code> block to prevent the Promise lib from catching the error, if I follow correctly.</p>", "body_text": "Right, but if I understand the chain correctly that means we aren't doing .catch() all the way up our Promises chain so somewhere the error is hidden...\nhttps://github.com/mozilla/node-firefox-connect/blob/master/index.js#L10\nThat would mean having to wrap the client.connect bit in a try/catch block to prevent the Promise lib from catching the error, if I follow correctly.", "body": "Right, but if I understand the chain correctly that means we aren't doing `.catch()` all the way up our Promises chain so somewhere the error is hidden...\n\nhttps://github.com/mozilla/node-firefox-connect/blob/master/index.js#L10\n\nThat would mean having to wrap the `client.connect` bit in a `try/catch` block to prevent the Promise lib from catching the error, if I follow correctly.\n"}